#include "2205091_visitor.h"


// Constructor & Destructor


MyVisitor::MyVisitor(int bucketSize, string outputFile) {
    symbolTable = new SymbolTable(bucketSize);
    codeStream.open(outputFile);
    labelCounter = 0;
    nextLocalOffset = -4;
    nextParamOffset = 8;
    currentFunctionName = "";

    // FASM ELF Executable Directive Initialization
    dataSection = "format ELF executable 3\nentry main\n\nsegment readable writeable\n";
    codeSection = "\nsegment readable executable\n\n";
}


// Helper Functions

bool MyVisitor::isGlobalScope() {
    return symbolTable->getCurrentScopeTable()->getParentScopeTable() == nullptr;
}

string MyVisitor::getOperand(string name) {
    SymbolInfo *symbol = symbolTable->lookUpSymbolInfo(name);
    if (symbol == nullptr) return name;

    if (symbol->getIsGlobal()) {
        return "[" + name + "]";
    } else {
        int offset = symbol->getOffset();
        if (offset < 0) {
            return "[ebp" + to_string(offset) + "]";
        } else {
            return "[ebp+" + to_string(offset) + "]";
        }
    }
}

string MyVisitor::newLabel() {
    return "L" + to_string(labelCounter++);
}

void MyVisitor::annotateLine(antlr4::ParserRuleContext *ctx) {
    if (ctx && ctx->getStart()) {
        int line = ctx->getStart()->getLine();
        codeSection += "; Line " + to_string(line) + "\n";
    }
}


// Selected Phase 1 Grammar Rules

// start : program ;
std::any MyVisitor::visitStartRule(CSubset_2205091Parser::StartRuleContext *ctx) {
    visit(ctx->program());

    if (codeStream.is_open()) {
        dataSection += "minus_sign db '-'\n";
        dataSection += "newline_str db 10\n";
        dataSection += "char_buffer db 0\n";
        codeStream << "; Intermediate Code Generated by 2205091 (FASM x86)\n";
        codeStream << dataSection;
        codeStream << codeSection;

        // Standard OUTDEC Procedure for Printing Integers (Linux sys_write)
        codeStream << "OUTDEC:\n";
        codeStream << "    push eax\n";
        codeStream << "    push ebx\n";
        codeStream << "    push ecx\n";
        codeStream << "    push edx\n";
        codeStream << "    cmp eax, 0\n";
        codeStream << "    jge .positive\n";
        codeStream << "    neg eax\n";
        codeStream << "    push eax\n";
        codeStream << "    mov eax, 4\n";
        codeStream << "    mov ebx, 1\n";
        codeStream << "    mov ecx, minus_sign\n";
        codeStream << "    mov edx, 1\n";
        codeStream << "    int 0x80\n";
        codeStream << "    pop eax\n";
        codeStream << ".positive:\n";
        codeStream << "    xor ecx, ecx\n";
        codeStream << "    mov ebx, 10\n";
        codeStream << ".divide_loop:\n";
        codeStream << "    xor edx, edx\n";
        codeStream << "    div ebx\n";
        codeStream << "    push edx\n";
        codeStream << "    inc ecx\n";
        codeStream << "    cmp eax, 0\n";
        codeStream << "    jnz .divide_loop\n";
        codeStream << ".print_loop:\n";
        codeStream << "    pop edx\n";
        codeStream << "    add edx, '0'\n";
        codeStream << "    push ecx\n";
        codeStream << "    mov [char_buffer], dl\n";
        codeStream << "    mov eax, 4\n";
        codeStream << "    mov ebx, 1\n";
        codeStream << "    mov ecx, char_buffer\n";
        codeStream << "    mov edx, 1\n";
        codeStream << "    int 0x80\n";
        codeStream << "    pop ecx\n";
        codeStream << "    loop .print_loop\n";
        codeStream << "    mov eax, 4\n";
        codeStream << "    mov ebx, 1\n";
        codeStream << "    mov ecx, newline_str\n";
        codeStream << "    mov edx, 1\n";
        codeStream << "    int 0x80\n";
        codeStream << "    pop edx\n";
        codeStream << "    pop ecx\n";
        codeStream << "    pop ebx\n";
        codeStream << "    pop eax\n";
        codeStream << "    ret\n\n";

        codeStream.close();
    }
    return nullptr;
}

// program : unit | program unit
std::any MyVisitor::visitProgramSingleUnit(CSubset_2205091Parser::ProgramSingleUnitContext *ctx) {
    return visit(ctx->unit());
}

std::any MyVisitor::visitProgramUnits(CSubset_2205091Parser::ProgramUnitsContext *ctx) {
    visit(ctx->program());
    visit(ctx->unit());
    return nullptr;
}

// unit : var_declaration | func_definition
std::any MyVisitor::visitUnitVarDecl(CSubset_2205091Parser::UnitVarDeclContext *ctx) {
    return visit(ctx->var_declaration());
}

std::any MyVisitor::visitUnitFuncDef(CSubset_2205091Parser::UnitFuncDefContext *ctx) {
    return visit(ctx->func_definition());
}

// func_definition : type_specifier ID LPAREN RPAREN compound_statement
std::any MyVisitor::visitFuncDefNoParams(CSubset_2205091Parser::FuncDefNoParamsContext *ctx) {
    visit(ctx->type_specifier());
    string funcName = ctx->ID()->getText();
    currentFunctionName = funcName;

    codeSection += funcName + ":\n";
    codeSection += "    push ebp\n";
    codeSection += "    mov ebp, esp\n";

    nextLocalOffset = -4;

    SymbolInfo *s = new SymbolInfo(funcName, "ID");
    s->setIsFunction(true);
    s->setIsDefined(true);
    s->setDataType(currentType);
    symbolTable->insertSymbolInfo(s);

    symbolTable->enterScope();
    visit(ctx->compound_statement());
    symbolTable->exitScope();

    if (funcName == "main") {
        codeSection += "    mov eax, 1\n";
        codeSection += "    xor ebx, ebx\n";
        codeSection += "    int 0x80\n";
    } else {
        codeSection += "    mov esp, ebp\n";
        codeSection += "    pop ebp\n";
        codeSection += "    ret\n";
    }
    return nullptr;
}

std::any MyVisitor::visitFuncDefWithParams(CSubset_2205091Parser::FuncDefWithParamsContext *ctx) {
    visit(ctx->type_specifier());
    string funcName = ctx->ID()->getText();
    currentFunctionName = funcName;

    codeSection += funcName + ":\n";
    codeSection += "    push ebp\n";
    codeSection += "    mov ebp, esp\n";

    nextLocalOffset = -4;
    nextParamOffset = 8;

    SymbolInfo *s = new SymbolInfo(funcName, "ID");
    s->setIsFunction(true);
    s->setIsDefined(true);
    s->setDataType(currentType);
    symbolTable->insertSymbolInfo(s);

    symbolTable->enterScope();
    if (ctx->parameter_list()) {
        visit(ctx->parameter_list());
    }
    visit(ctx->compound_statement());
    symbolTable->exitScope();

    if (funcName == "main") {
        codeSection += "    mov eax, 1\n";
        codeSection += "    xor ebx, ebx\n";
        codeSection += "    int 0x80\n";
    } else {
        codeSection += "    mov esp, ebp\n";
        codeSection += "    pop ebp\n";
        codeSection += "    ret\n";
    }
    return nullptr;
}

// compound_statement : LCURL statements RCURL | LCURL RCURL
std::any MyVisitor::visitCompoundStmtWithStmts(CSubset_2205091Parser::CompoundStmtWithStmtsContext *ctx) {
    return visit(ctx->statements());
}

std::any MyVisitor::visitCompoundStmtEmpty(CSubset_2205091Parser::CompoundStmtEmptyContext *ctx) {
    return nullptr;
}

// var_declaration : type_specifier declaration_list SEMICOLON
std::any MyVisitor::visitVarDeclaration(CSubset_2205091Parser::VarDeclarationContext *ctx) {
    if (!isGlobalScope()) {
        annotateLine(ctx);
    }
    visit(ctx->type_specifier());
    visit(ctx->declaration_list());
    return nullptr;
}

// type_specifier : INT | VOID
std::any MyVisitor::visitTypeInt(CSubset_2205091Parser::TypeIntContext *ctx) {
    currentType = "INT";
    return string("INT");
}

std::any MyVisitor::visitTypeVoid(CSubset_2205091Parser::TypeVoidContext *ctx) {
    currentType = "VOID";
    return string("VOID");
}

// declaration_list : ID | declaration_list COMMA ID
std::any MyVisitor::visitDeclVar(CSubset_2205091Parser::DeclVarContext *ctx) {
    string name = ctx->ID()->getText();
    SymbolInfo *s = new SymbolInfo(name, "ID");
    s->setDataType(currentType);

    if (isGlobalScope()) {
        s->setIsGlobal(true);
        dataSection += "    " + name + " dd 0\n";
    } else {
        s->setIsGlobal(false);
        s->setOffset(nextLocalOffset);
        nextLocalOffset -= 4;
        codeSection += "    sub esp, 4\n";
    }

    symbolTable->insertSymbolInfo(s);
    return name;
}

std::any MyVisitor::visitDeclListVar(CSubset_2205091Parser::DeclListVarContext *ctx) {
    visit(ctx->declaration_list());   

    string name = ctx->ID()->getText();
    SymbolInfo *s = new SymbolInfo(name, "ID");
    s->setDataType(currentType);

    if (isGlobalScope()) {
        s->setIsGlobal(true);
        dataSection += "    " + name + " dd 0\n";
    } else {
        s->setIsGlobal(false);
        s->setOffset(nextLocalOffset);
        nextLocalOffset -= 4;
        codeSection += "    sub esp, 4\n";
    }
    symbolTable->insertSymbolInfo(s);
    return nullptr;
}

// parameter_list : ParamSingle implementation
std::any MyVisitor::visitParamSingle(CSubset_2205091Parser::ParamSingleContext *ctx) {
    string varName = ctx->ID()->getText();
    SymbolInfo *info = new SymbolInfo(varName, "ID");
    info->setDataType(currentType);
    info->setIsGlobal(false);
    info->setOffset(nextParamOffset);
    nextParamOffset += 4;
    symbolTable->insertSymbolInfo(info);
    return nullptr;
}

// statements : statement | statements statement
std::any MyVisitor::visitSingleStmt(CSubset_2205091Parser::SingleStmtContext *ctx) {
    return visit(ctx->statement());
}

std::any MyVisitor::visitMultipleStmts(CSubset_2205091Parser::MultipleStmtsContext *ctx) {
    visit(ctx->statements());
    visit(ctx->statement());
    return nullptr;
}

// statement : var_declaration | expression_statement | compound_statement | PRINTLN | RETURN
std::any MyVisitor::visitStmtVarDecl(CSubset_2205091Parser::StmtVarDeclContext *ctx) {
    return visit(ctx->var_declaration());
}

std::any MyVisitor::visitStmtExpr(CSubset_2205091Parser::StmtExprContext *ctx) {
    return visit(ctx->expression_statement());
}

std::any MyVisitor::visitStmtCompound(CSubset_2205091Parser::StmtCompoundContext *ctx) {
    symbolTable->enterScope();
    visit(ctx->compound_statement());
    symbolTable->exitScope();
    return nullptr;
}

std::any MyVisitor::visitStmtPrintln(CSubset_2205091Parser::StmtPrintlnContext *ctx) {
    annotateLine(ctx);
    string varName = ctx->ID()->getText();
    string operand = getOperand(varName);

    codeSection += "    mov eax, " + operand + "\n";
    codeSection += "    call OUTDEC\n";
    return nullptr;
}

std::any MyVisitor::visitStmtReturn(CSubset_2205091Parser::StmtReturnContext *ctx) {
    annotateLine(ctx);
    visit(ctx->expression());
    codeSection += "    pop eax\n";

    if (currentFunctionName == "main") {
        codeSection += "    mov eax, 1\n";
        codeSection += "    xor ebx, ebx\n";
        codeSection += "    int 0x80\n";
    } else {
        codeSection += "    mov esp, ebp\n";
        codeSection += "    pop ebp\n";
        codeSection += "    ret\n";
    }
    return nullptr;
}

// expression_statement : SEMICOLON | expression SEMICOLON
std::any MyVisitor::visitExprStmtEmpty(CSubset_2205091Parser::ExprStmtEmptyContext *ctx) {
    return nullptr;
}

std::any MyVisitor::visitExprStmtExpr(CSubset_2205091Parser::ExprStmtExprContext *ctx) {
    annotateLine(ctx);
    visit(ctx->expression());
    codeSection += "    pop eax\n";
    return nullptr;
}

// variable : ID
std::any MyVisitor::visitVarSimple(CSubset_2205091Parser::VarSimpleContext *ctx) {
    return ctx->ID()->getText();
}

// expression : logic_expression | variable ASSIGNOP logic_expression
std::any MyVisitor::visitExprLogic(CSubset_2205091Parser::ExprLogicContext *ctx) {
    return visit(ctx->logic_expression());
}

std::any MyVisitor::visitExprAssign(CSubset_2205091Parser::ExprAssignContext *ctx) {
    string varName = std::any_cast<string>(visit(ctx->variable()));
    visit(ctx->logic_expression());
    string operand = getOperand(varName);
    codeSection += "    pop eax\n";
    codeSection += "    mov " + operand + ", eax\n";
    codeSection += "    push eax\n";   
    return nullptr;
}

// logic_expression : rel_expression | rel_expression LOGICOP rel_expression
std::any MyVisitor::visitLogicExprRel(CSubset_2205091Parser::LogicExprRelContext *ctx) {
    return visit(ctx->rel_expression());
}

std::any MyVisitor::visitLogicExprBinary(CSubset_2205091Parser::LogicExprBinaryContext *ctx) {
    visit(ctx->left);
    visit(ctx->right);

    codeSection += "    pop ebx\n";
    codeSection += "    pop eax\n";

    string op = ctx->LOGICOP()->getText();
    string labelFalse = newLabel();
    string labelEnd = newLabel();

    if (op == "&&") {
        codeSection += "    cmp eax, 0\n";
        codeSection += "    je " + labelFalse + "\n";
        codeSection += "    cmp ebx, 0\n";
        codeSection += "    je " + labelFalse + "\n";
        codeSection += "    push 1\n";
        codeSection += "    jmp " + labelEnd + "\n";
        codeSection += labelFalse + ":\n";
        codeSection += "    push 0\n";
        codeSection += labelEnd + ":\n";
    } else if (op == "||") {
        string labelTrue = newLabel();
        codeSection += "    cmp eax, 0\n";
        codeSection += "    jne " + labelTrue + "\n";
        codeSection += "    cmp ebx, 0\n";
        codeSection += "    jne " + labelTrue + "\n";
        codeSection += "    push 0\n";
        codeSection += "    jmp " + labelEnd + "\n";
        codeSection += labelTrue + ":\n";
        codeSection += "    push 1\n";
        codeSection += labelEnd + ":\n";
    }
    return nullptr;
}

// rel_expression : simple_expression | simple_expression RELOP simple_expression
std::any MyVisitor::visitRelExprSimple(CSubset_2205091Parser::RelExprSimpleContext *ctx) {
    return visit(ctx->simple_expression());
}

std::any MyVisitor::visitRelExprBinary(CSubset_2205091Parser::RelExprBinaryContext *ctx) {
    visit(ctx->simple_expression(0));
    visit(ctx->simple_expression(1));

    codeSection += "    pop ebx\n";
    codeSection += "    pop eax\n";
    codeSection += "    cmp eax, ebx\n";

    string op = ctx->RELOP()->getText();
    string labelTrue = newLabel();
    string labelEnd = newLabel();

    if (op == "<") codeSection += "    jl " + labelTrue + "\n";
    else if (op == "<=") codeSection += "    jle " + labelTrue + "\n";
    else if (op == ">") codeSection += "    jg " + labelTrue + "\n";
    else if (op == ">=") codeSection += "    jge " + labelTrue + "\n";
    else if (op == "==") codeSection += "    je " + labelTrue + "\n";
    else if (op == "!=") codeSection += "    jne " + labelTrue + "\n";

    codeSection += "    push 0\n";
    codeSection += "    jmp " + labelEnd + "\n";
    codeSection += labelTrue + ":\n";
    codeSection += "    push 1\n";
    codeSection += labelEnd + ":\n";

    return nullptr;
}

// simple_expression : term | simple_expression ADDOP term
std::any MyVisitor::visitSimpleExprTerm(CSubset_2205091Parser::SimpleExprTermContext *ctx) {
    return visit(ctx->term());
}

std::any MyVisitor::visitSimpleExprAdd(CSubset_2205091Parser::SimpleExprAddContext *ctx) {
    visit(ctx->simple_expression());
    visit(ctx->term());

    codeSection += "    pop ebx\n";
    codeSection += "    pop eax\n";

    string op = ctx->ADDOP()->getText();
    if (op == "+") {
        codeSection += "    add eax, ebx\n";
    } else if (op == "-") {
        codeSection += "    sub eax, ebx\n";
    }
    codeSection += "    push eax\n";
    return nullptr;
}

// term : unary_expression | term MULOP unary_expression
std::any MyVisitor::visitTermUnary(CSubset_2205091Parser::TermUnaryContext *ctx) {
    return visit(ctx->unary_expression());
}

std::any MyVisitor::visitTermMul(CSubset_2205091Parser::TermMulContext *ctx) {
    visit(ctx->term());
    visit(ctx->unary_expression());

    codeSection += "    pop ebx\n";
    codeSection += "    pop eax\n";

    string op = ctx->MULOP()->getText();
    if (op == "*") {
        codeSection += "    imul ebx\n";
        codeSection += "    push eax\n";
    } else if (op == "/") {
        codeSection += "    cdq\n";
        codeSection += "    idiv ebx\n";
        codeSection += "    push eax\n";
    } else if (op == "%") {
        codeSection += "    cdq\n";
        codeSection += "    idiv ebx\n";
        codeSection += "    push edx\n";
    }
    return nullptr;
}

// unary_expression : ADDOP unary_expression | NOT unary_expression | factor
std::any MyVisitor::visitUnaryAdd(CSubset_2205091Parser::UnaryAddContext *ctx) {
    visit(ctx->unary_expression());
    if (ctx->ADDOP()->getText() == "-") {
        codeSection += "    pop eax\n";
        codeSection += "    neg eax\n";
        codeSection += "    push eax\n";
    }
    return nullptr;
}

std::any MyVisitor::visitUnaryNot(CSubset_2205091Parser::UnaryNotContext *ctx) {
    visit(ctx->unary_expression());
    codeSection += "    pop eax\n";
    codeSection += "    cmp eax, 0\n";

    string labelZero = newLabel();
    string labelEnd = newLabel();

    codeSection += "    je " + labelZero + "\n";
    codeSection += "    push 0\n";
    codeSection += "    jmp " + labelEnd + "\n";
    codeSection += labelZero + ":\n";
    codeSection += "    push 1\n";
    codeSection += labelEnd + ":\n";
    return nullptr;
}

std::any MyVisitor::visitUnaryFactor(CSubset_2205091Parser::UnaryFactorContext *ctx) {
    return visit(ctx->factor());
}

// factor : variable | ID LPAREN argument_list RPAREN | LPAREN expression RPAREN | CONST_INT | CONST_FLOAT | variable INCOP | variable DECOP
std::any MyVisitor::visitFactorVar(CSubset_2205091Parser::FactorVarContext *ctx) {
    string varName = std::any_cast<string>(visit(ctx->variable()));
    string operand = getOperand(varName);
    codeSection += "    mov eax, " + operand + "\n";
    codeSection += "    push eax\n";
    return nullptr;
}

std::any MyVisitor::visitFactorFuncCall(CSubset_2205091Parser::FactorFuncCallContext *ctx) {
    // string funcName = ctx->ID()->getText();
    // if (ctx->argument_list()) {
    //     visit(ctx->argument_list());
    // }
    // codeSection += "    call " + funcName + "\n";
    // codeSection += "    push eax\n";
    return nullptr;
}

std::any MyVisitor::visitFactorParen(CSubset_2205091Parser::FactorParenContext *ctx) {
    return visit(ctx->expression());
}

std::any MyVisitor::visitFactorConstInt(CSubset_2205091Parser::FactorConstIntContext *ctx) {
    codeSection += "    push " + ctx->CONST_INT()->getText() + "\n";
    return nullptr;
}

std::any MyVisitor::visitFactorConstFloat(CSubset_2205091Parser::FactorConstFloatContext *ctx) {
    codeSection += "    push " + ctx->CONST_FLOAT()->getText() + "\n";
    return nullptr;
}

std::any MyVisitor::visitFactorInc(CSubset_2205091Parser::FactorIncContext *ctx) {
    string varName = std::any_cast<string>(visit(ctx->variable()));
    string operand = getOperand(varName);

    codeSection += "    mov eax, " + operand + "\n";
    codeSection += "    push eax\n";
    codeSection += "    inc dword " + operand + "\n";
    return nullptr;
}

std::any MyVisitor::visitFactorDec(CSubset_2205091Parser::FactorDecContext *ctx) {
    string varName = std::any_cast<string>(visit(ctx->variable()));
    string operand = getOperand(varName);

    codeSection += "    mov eax, " + operand + "\n";
    codeSection += "    push eax\n";
    codeSection += "    dec dword " + operand + "\n";
    return nullptr;
}


// Unused / Excluded Grammar Rules 


std::any MyVisitor::visitUnitFuncDecl(CSubset_2205091Parser::UnitFuncDeclContext *ctx) { return nullptr; }
std::any MyVisitor::visitFuncDeclWithParams(CSubset_2205091Parser::FuncDeclWithParamsContext *ctx) { return nullptr; }
std::any MyVisitor::visitFuncDeclNoParams(CSubset_2205091Parser::FuncDeclNoParamsContext *ctx) { return nullptr; }

std::any MyVisitor::visitParamListMulti(CSubset_2205091Parser::ParamListMultiContext *ctx) { return nullptr; }
std::any MyVisitor::visitParamListMultiUnnamed(CSubset_2205091Parser::ParamListMultiUnnamedContext *ctx) { return nullptr; }
std::any MyVisitor::visitParamSingleUnnamed(CSubset_2205091Parser::ParamSingleUnnamedContext *ctx) { return nullptr; }
std::any MyVisitor::visitParamADDOPError(CSubset_2205091Parser::ParamADDOPErrorContext *ctx) { return nullptr; }

std::any MyVisitor::visitTypeFloat(CSubset_2205091Parser::TypeFloatContext *ctx) { return nullptr; }

std::any MyVisitor::visitDeclArray(CSubset_2205091Parser::DeclArrayContext *ctx) { return nullptr; }
std::any MyVisitor::visitDeclListArray(CSubset_2205091Parser::DeclListArrayContext *ctx) { return nullptr; }
std::any MyVisitor::visitDeclADDOPError(CSubset_2205091Parser::DeclADDOPErrorContext *ctx) { return nullptr; }

std::any MyVisitor::visitStmtFor(CSubset_2205091Parser::StmtForContext *ctx) { return nullptr; }
std::any MyVisitor::visitStmtIf(CSubset_2205091Parser::StmtIfContext *ctx) { return nullptr; }
std::any MyVisitor::visitStmtIfElse(CSubset_2205091Parser::StmtIfElseContext *ctx) { return nullptr; }
std::any MyVisitor::visitStmtWhile(CSubset_2205091Parser::StmtWhileContext *ctx) { return nullptr; }

std::any MyVisitor::visitExprStmtNoSemiError(CSubset_2205091Parser::ExprStmtNoSemiErrorContext *ctx) { return nullptr; }
std::any MyVisitor::visitVarArray(CSubset_2205091Parser::VarArrayContext *ctx) { return nullptr; }

std::any MyVisitor::visitSimpleExprAddAssignError(CSubset_2205091Parser::SimpleExprAddAssignErrorContext *ctx) { return nullptr; }

std::any MyVisitor::visitArgListExpr(CSubset_2205091Parser::ArgListExprContext *ctx) { return visit(ctx->arguments()); }
std::any MyVisitor::visitArgListEmpty(CSubset_2205091Parser::ArgListEmptyContext *ctx) { return nullptr; }
std::any MyVisitor::visitArgsMulti(CSubset_2205091Parser::ArgsMultiContext *ctx) {
    visit(ctx->arguments());
    visit(ctx->logic_expression());
    return nullptr;
}
std::any MyVisitor::visitArgsSingle(CSubset_2205091Parser::ArgsSingleContext *ctx) {
    return visit(ctx->logic_expression());
}